# Generated by Django 4.1.4 on 2023-01-28 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_saytlar_alter_word_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='word',
            name='eng',
            field=models.BooleanField(default=False),
        ),
    ]
